### PR TITLE
fix monitoring

### PR DESCRIPTION
**Pull request by ilkerhalil**

### CODE REVIEW

**Comment by hrenard** [comment]
Thanks ! I didn't catch that `JVB_ENABLE_APIS` gotten removed. Now we need `COLIBRI_REST_ENABLED` and `SHUTDOWN_REST_ENABLED`. 
Do you want to remove `JVB_ENABLE_APIS` and add `SHUTDOWN_REST_ENABLED` in your PR ? Otherwise, I will do it.

**Comment by sapkra** [comment]
@ilkerhalil Just to let you now: we are having a discussion about renaming the env var in future releases, because it's not only enabling the colibri API: https://github.com/jitsi/docker-jitsi-meet/issues/1163

**Comment by ilkerhalil** [comment]
> _No description provided._

You can add. Thank you.

**Comment by ilkerhalil** [comment]
> renaming



> @ilkerhalil Just to let you know: we are having a discussion about renaming the env var in future releases, because it's not just enabling the colibri API: [jitsi/docker-jitsi-meet#1163](https://github.com/jitsi/docker-jitsi-meet/issues/1163)

I guess it has changed a lot because of log4j. It may be necessary to update all of them from top to bottom. Looks like the latest version of Jibri is recording too...

**Comment by hrenard** [comment]
I'm closing in favor of #5. Thanks anyway.

**Pull request closed without merging**
